### ISSUE TITLE
cv_bridge / libffi crashes visualization node on SCOUT

### ISSUE THREAD

**Issue by kevin-chau** [kevin-chau/person_following_orin#10]
```
Traceback (most recent call last):
  File "/home/castro/person_following_orin/src/monocular_person_following/scripts/visualization.py", line 232, in <module>
    main()
  File "/home/castro/person_following_orin/src/monocular_person_following/scripts/visualization.py", line 227, in main
    node.spin()
  File "/home/castro/person_following_orin/src/monocular_person_following/scripts/visualization.py", line 217, in spin
    img_msg = cv_bridge.CvBridge().cv2_to_imgmsg(self.image.astype(numpy.uint8), 'bgr8')
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 266, in cv2_to_imgmsg
    if self.cvtype_to_name[self.encoding_to_cvtype2(encoding)] != cv_type:
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 91, in encoding_to_cvtype2
    from cv_bridge.boost.cv_bridge_boost import getCvType
ImportError: /lib/aarch64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
[visualization_node-4] process has died [pid 59745, exit code 1, cmd /home/castro/person_following_orin/src/monocular_person_following/scripts/visualization.py image_rect:=/top_front_camera/qhd/image_rect __name:=visualization_node __log:=/home/castro/.ros/log/25d6d8f4-18a5-11ef-99db-90e868844cb3/visualization_node-4.log].
log file: /home/castro/.ros/log/25d6d8f4-18a5-11ef-99db-90e868844cb3/visualization_node-4*.log
```

**Comment by kevin-chau** [comment]
Making a python 3.8.10 environment seems to fix this, as suggested by this issue: https://github.com/ros-perception/vision_opencv/issues/509
